# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-18 10:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ItemsModels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_logo', models.FileField(upload_to='')),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=500)),
                ('price_of_income', models.IntegerField()),
                ('price_of_sold', models.IntegerField()),
            ],
        ),
    ]
